[project]
name = "logfire-vscode"
version = "2026.6.0"
description = "A Visual Studio Code extension for Pydantic Logfire"
authors = [
    {name = "Victorien Plot", email = "contact@vctrn.dev"},
]
readme = "README.md"
requires-python = ">=3.9"
dependencies = ["logfire-lsp==0.0.4"]

[dependency-groups]
dev = [
    "requests>=2.32.4",
    "requirements-parser>=0.13.0",
    "wheel-filename>=1.4.2",
]


[tool.uv]
required-version = ">=0.7.2"
default-groups = ["dev"]
# Allow prereleases for pygls2.0.0alpha pinning lsprotocol==2025.0.0rc1:
prerelease = "allow"

[tool.ruff]
line-length = 120
target-version = "py39"
include = ["scripts/*.py", "bundled/tool/*.py", "**/pyproject.toml"]

[tool.ruff.format]
quote-style = "single"

[tool.ruff.lint]
select = [
    "E",      # pycodestyle (E)
    "W",      # pycodestyle (W)
    "F",      # Pyflakes
    "UP",     # pyupgrade
    "I",      # isort
    "PL",     # Pylint
    "RUF",    # Ruff
    "YTT",    # flake8-2020
    "B",      # flake8-bugbear
    "C4",     # flake8-comprehensions
    "T10",    # flake8-debugger
    "FA",     # flake8-future-annotations
    "PIE",    # flake8-pie
    "PYI",    # flake8-pyi
    "Q",      # flake8-quotes
    "RSE",    # flake8-raise
    "PTH",    # flake8-use-pathlib
]
ignore = [
    "PLR2004",
    "PLC0415",
    "PTH112",
    "T100",
]

[tool.ruff.lint.flake8-quotes]
inline-quotes = "single"
